[package]
name = "mirror"
version = "0.2.0-beta5"
authors = ["ko1N <ko1N1337@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "^4.0", features = ["cargo"] }
simplelog = "^0.12"
log = "^0.4"
parking_lot = { version = "0.12", features = [ "hardware-lock-elision" ] }

# memflow
memflow = { version = "^0.2.0-beta9", features = ["plugins"] }
memflow-win32 = { version = "^0.2.0-beta", optional = true }
memflow-qemu = { version = "^0.2.0-beta", optional = true }
mirror-dto = { path = "../mirror-dto" }

# gui
egui = "0.20.0"
eframe = "0.20.0"
epaint = "0.20.0"
egui-notify = "0.5.0"

thread-priority = "^0.10"
regex = "^1.5" # TODO: replace with pattern-scanner lib

# renderer
sdl2 = { version = "0.35.1", features = [] }
glium = "0.26.0"
glium_text_rusttype = "0.3.3"
cgmath = "^0.18.0"
image = "^0.23.14"
frame_counter = "0.1.2"
notify = { version = "^4.0.17", optional = true }

[features]
default = []
memflow-static = ["memflow-win32", "memflow-qemu"]
shader-reload = ["notify"]
