[package]
name = "mirror"
version = "0.1.0"
authors = ["ko1N <ko1N1337@gmail.com>"]
edition = "2018"

[build-dependencies]
clap = { version = "2.33.0", features = ["yaml"] }

[dependencies]
memflow = { git = "https://github.com/memflow/memflow", branch = "next" }
clap = { version = "2.33.0", features = ["yaml"] }
simple_logger = "1.0"
log = "0.4.8"
regex = "1" # TODO: replace with pattern-scanner lib
mirror_dto = { path = "../mirror-dto" }

# renderer
sdl2 = { version = "0.34.0", features = ["bundled", "static-link"] }
glium = "0.26"
glium_text_rusttype = "0.3.3"
cgmath = "0.17" # TODO: replace?
notify = "4.0"
image = "0.23"
