[package]
name = "mirror"
version = "0.2.0-beta5"
authors = ["ko1N <ko1N1337@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "^4.0", features = ["cargo"] }
simplelog = "^0.12"
log = "^0.4"
parking_lot = { version = "0.12", features = [ "hardware-lock-elision" ] }
frame_counter = "0.1.2"

# memflow
memflow = { version = "^0.2.0-beta9", features = ["plugins"] }
memflow-win32 = { version = "^0.2.0-beta", optional = true }
memflow-qemu = { version = "^0.2.0-beta", optional = true }
mirror-dto = { path = "../mirror-dto" }

# gui
egui = "0.20.0"
eframe = "0.20.0"
epaint = "0.20.0"
egui-notify = "0.5.0"
image = "^0.24"

thread-priority = "^0.10"
regex = "^1.5" # TODO: replace with pattern-scanner lib

[features]
default = []
memflow-static = ["memflow-win32", "memflow-qemu"] # TODO: 
