[package]
name = "mirror"
version = "0.1.0"
authors = ["ko1N <ko1N1337@gmail.com>"]
edition = "2018"

[build-dependencies]
clap = { version = "2.33.0", features = ["yaml"] }

[dependencies]
memflow = { git = "https://github.com/memflow/memflow", branch = "next", features = ["plugins"] }
memflow-win32 = { git = "https://github.com/memflow/memflow", branch = "next", optional = true }
memflow-qemu-procfs = { git = "https://github.com/memflow/memflow-qemu-procfs", branch = "next", optional = true }
mirror-dto = { path = "../mirror-dto" }
clap = { version = "2.33.0", features = ["yaml"] }
simple_logger = "1.0"
log = "0.4.8"
regex = "1" # TODO: replace with pattern-scanner lib

# renderer
sdl2 = { version = "0.35.1", features = [] }
glium = "0.26"
glium_text_rusttype = "0.3.3"
cgmath = "0.17"
image = "0.23"
frame_counter = "0.1.2"
notify = { version = "4.0", optional = true }

[features]
default = []
memflow-static = ["memflow-win32", "memflow-qemu-procfs"]
shader-reload = ["notify"]
